TimeFormat:
  Weeks: "&a%weeks%w"
  Days: "&a%days%d"
  Hours: "&a%hours%h"
  Minutes: "&a%minutes%m"
  Seconds: "&a%seconds%s"
  Separator: "&7 "
  LastSeparator: "&7 and "
  Show-Zero-Values: false

# Crop growth times in seconds (e.g., 600 = 10 minutes)
CropGrowthTimes:
  WHEAT: 600
  CARROTS: 600
  POTATOES: 600
  BEETROOTS: 600
  NETHER_WART: 600
  COCOA: 600
  MELON_STEM: 600
  PUMPKIN_STEM: 600
  CACTUS: 600
  SUGAR_CANE: 600

CropSellPrices:
  WHEAT: 10
  CARROT: 10
  POTATO: 10
  BEETROOT: 10
  NETHER_WART: 10
  COCOA: 10
  MELON: 10
  PUMPKIN: 10
  CACTUS: 10
  SUGAR_CANE: 10

CustomCropItem:
  Name: "&aCrop: %crop_name%"
  Lore:
    - "&7Harvested from a custom crop."
    - "&7Price: %price% Cubes."
    - ""
    - "&eYou can sell it to the black-market NPC at spawn!"

CropInfoGUI:
  Size: 45
  Title: "&6&lGrowth Status"
  Fill-Background:
    Material: LIME_STAINED_GLASS_PANE
    Name: " "
  Barrier:
    Material: GREEN_STAINED_GLASS_PANE
    Name: " "
  Items:
    StatusHeader:
      Slot: 20
      Material: CLOCK
      Name: "&e&lGrowth Status"
      Lore:
        - "&7Crop Type: &f%crop_type%"
        - "&7Time Remaining: &f%time_remaining%"
        - "&7Growth Percentage: &f%growth_percentage%"
    CropIcon:
      Slot: 24
      Material: "%crop_icon%"
      Name: "&a%crop_type%"
      Lore:
        - "&7Planted: &f%planted_time%"
    CloseButton:
      Slot: 40
      Material: BARRIER
      Name: "&cClose"
      Action: close


# Messages for cubes currency
Messages:
  Prefix: "&8[<GRADIENT:00FFFF>Crops</GRADIENT:ADD8E6>&8]"
  Balance: "%prefix% <GRADIENT:00FFFF>You have</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%cubes%</GRADIENT:ADD8E6> <GRADIENT:00FFFF>cubes.</GRADIENT:ADD8E6>"
  BalanceOther: "%prefix% <GRADIENT:00FFFF>%player% has</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%cubes%</GRADIENT:ADD8E6> <GRADIENT:00FFFF>cubes.</GRADIENT:ADD8E6>"
  Give: "%prefix% <GRADIENT:00FFFF>You gave</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%amount%</GRADIENT:ADD8E6> <GRADIENT:00FFFF>cubes to</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%player%</GRADIENT:ADD8E6>."
  Receive: "%prefix% <GRADIENT:00FFFF>You received</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%amount%</GRADIENT:ADD8E6> <GRADIENT:00FFFF>cubes from</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%player%</GRADIENT:ADD8E6>."
  Set: "%prefix% <GRADIENT:00FFFF>You set</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%player%</GRADIENT:ADD8E6>'s <GRADIENT:00FFFF>balance to</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%amount%</GRADIENT:ADD8E6> <GRADIENT:00FFFF>cubes.</GRADIENT:ADD8E6>"
  Pay: "%prefix% <GRADIENT:00FFFF>You paid</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%amount%</GRADIENT:ADD8E6> <GRADIENT:00FFFF>cubes to</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%player%</GRADIENT:ADD8E6>."
  InsufficientFunds: "%prefix% <GRADIENT:00FFFF>You don't have enough cubes to complete this transaction.</GRADIENT:ADD8E6>"
  SoldCrops: "<GRADIENT:00FFFF>You sold</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%amount%</GRADIENT:ADD8E6> <GRADIENT:00FFFF>crops for</GRADIENT:ADD8E6> <GRADIENT:00FFFF>%total%</GRADIENT:ADD8E6> <GRADIENT:00FFFF>cubes.</GRADIENT:ADD8E6>"
  NoCropsToSell: "<GRADIENT:00FFFF>You don't have any crops to sell.</GRADIENT:ADD8E6>"
  PlayerOnlyCommand: "%prefix% <GRADIENT:00FFFF>This command can only be used by players.</GRADIENT:ADD8E6>"
  NoPermission: "%prefix% <GRADIENT:00FFFF>You do not have permission to use this command.</GRADIENT:ADD8E6>"
  InvalidArguments: "%prefix% <GRADIENT:00FFFF>Invalid arguments provided.</GRADIENT:ADD8E6>"
  InvalidNumber: "%prefix% <GRADIENT:00FFFF>Please provide a valid number.</GRADIENT:ADD8E6>"
  PlayerNotFound: "%prefix% <GRADIENT:00FFFF>Player not found.</GRADIENT:ADD8E6>"
  InvalidCommand: "%prefix% <GRADIENT:00FFFF>Invalid command."
  Reload: "%prefix% &aPlugin configuration reloaded successfully."
  ShopRotated: "%prefix% &aRotating shop items have been rotated."
  ItemOutOfStock: "%prefix% <GRADIENT:00FFFF>This item is currently out of stock.</GRADIENT:ADD8E6>"
  InsufficientLevel: "%prefix% <GRADIENT:00FFFF>This item requires you to first purchase a level %required_level% crop</GRADIENT:ADD8E6>"
  ItemOutOfStockPlaceholder: "&cOUT OF STOCK"


# Rotating shop configuration
RotatingShop:
  Size: 45
  Title: "<GRADIENT:00FFFF>&lRotating Shop</GRADIENT:ADD8E6>"
  ResetTimes:
    - "00:00"
    - "12:00"
    # - "Sunday 00:00" if you want it to reset weekly on Sunday at 00:00
    # - "1 00:00" if you want it to reset monthly on the 1st of every month at 00:00
  Rarities:
    Awesome:
      Chance: 5
      DisplayName: "&6Awesome"
    Epic:
      Chance: 10
      DisplayName: "&5Epic"
    Rare:
      Chance: 25
      DisplayName: "&9Rare"
    Common:
      Chance: 60
      DisplayName: "&aCommon"
  Slots: [20, 21, 22, 23, 24] # Slots where items will be displayed in the shop

  Fill-Background:
    Material: CYAN_STAINED_GLASS_PANE
    Name: " "
  Barrier:
    Material: LIGHT_BLUE_STAINED_GLASS_PANE
    Name: " "
  Items: # Decoration items in the shop
    'Rotating-Shop':
      Slot: 4
      Material: CLOCK
      Name: "&8⋗ <GRADIENT:00FFFF>Rotating Shop</GRADIENT:ADD8E6> &8⋖"
      Lore:
        - "&8&l❙ &7Next Rotation in: <GRADIENT:00FFFF>%rotation_time%</GRADIENT:ADD8E6>"
        - "&8&l❙ &7Balance: &f%balance% <GRADIENT:00FFFF>Cubes</GRADIENT:ADD8E6>"
        - " "
        - "&8&l❙ &eClick to close the shop."
      Action: close

  ShopItems:
    'CropCarrot':
      Rarity: Common
      Material: CARROT
      Name: "&aCarrot"
      Lore:
        - "&7A fresh crop."
        - ""
        - "&8&l❙ &aRarity: %rarity%"
        - "&8&l❙ &aPrice: &210 &aCubes"
        - "&8&l❙ &aLevel Required: &f1"
        - "&8&l❙ &aPersonal Stock: &f%personal_stock%"
        - "&8&l❙ &aGlobal Stock: &f%global_stock%"
        - ""
        - "&8&l❙ &eClick here to buy"
      Glow: false
      Price: 10
      PersonalStock: 1
      GlobalStock: 50
      RequiredLevel: 1
      Actions:
        - "{console} give %player% carrot 1"
        - "{message} &aYou received a Carrot!"
        - "{close}"

    'CropPotato':
      Rarity: Common
      Material: POTATO
      Name: "&ePotato"
      Lore:
        - "&7A fresh crop."
        - ""
        - "&8&l❙ &aRarity: %rarity%"
        - "&8&l❙ &aPrice: &210 &aCubes"
        - "&8&l❙ &aLevel Required: &f2"
        - "&8&l❙ &aPersonal Stock: &f%personal_stock%"
        - "&8&l❙ &aGlobal Stock: &f%global_stock%"
        - ""
        - "&8&l❙ &eClick here to buy"
      Glow: false
      Price: 10
      PersonalStock: 1
      GlobalStock: 50
      RequiredLevel: 2
      Actions:
        - "{console} give %player% potato 1"
        - "{message} &aYou received a Potato!"
        - "{close}"

    'CropWheat':
      Rarity: Common
      Material: WHEAT
      Name: "&6Wheat"
      Lore:
        - "&7A fresh crop."
        - ""
        - "&8&l❙ &aRarity: %rarity%"
        - "&8&l❙ &aPrice: &210 &aCubes"
        - "&8&l❙ &aLevel Required: &f3"
        - "&8&l❙ &aPersonal Stock: &f%personal_stock%"
        - "&8&l❙ &aGlobal Stock: &f%global_stock%"
        - ""
        - "&8&l❙ &eClick here to buy"
      Glow: false
      Price: 10
      PersonalStock: 1
      GlobalStock: 50
      RequiredLevel: 3
      Actions:
        - "{console} give %player% wheat 1"
        - "{message} &aYou received Wheat!"
        - "{close}"

    'CropNetherWart':
      Rarity: Rare
      Material: NETHER_WART
      Name: "&cNether Wart"
      Lore:
        - "&7A fresh crop."
        - ""
        - "&8&l❙ &aRarity: %rarity%"
        - "&8&l❙ &aPrice: &210 &aCubes"
        - "&8&l❙ &aLevel Required: &f4"
        - "&8&l❙ &aPersonal Stock: &f%personal_stock%"
        - "&8&l❙ &aGlobal Stock: &f%global_stock%"
        - ""
        - "&8&l❙ &eClick here to buy"
      Glow: false
      Price: 10
      PersonalStock: 1
      GlobalStock: 50
      RequiredLevel: 4
      Actions:
        - "{console} give %player% nether_wart 1"
        - "{message} &aYou received Nether Wart!"
        - "{close}"

    'CropCactus':
      Rarity: Rare
      Material: CACTUS
      Name: "&2Cactus"
      Lore:
        - "&7A fresh crop."
        - ""
        - "&8&l❙ &aRarity: %rarity%"
        - "&8&l❙ &aPrice: &210 &aCubes"
        - "&8&l❙ &aLevel Required: &f5"
        - "&8&l❙ &aPersonal Stock: &f%personal_stock%"
        - "&8&l❙ &aGlobal Stock: &f%global_stock%"
        - ""
        - "&8&l❙ &eClick here to buy"
      Glow: false
      Price: 10
      PersonalStock: 1
      GlobalStock: 50
      RequiredLevel: 5
      Actions:
        - "{console} give %player% cactus 1"
        - "{message} &aYou received a Cactus!"
        - "{close}"

    'CropSugarCane':
      Rarity: Epic
      Material: SUGAR_CANE
      Name: "&fSugar Cane"
      Lore:
        - "&7A fresh crop."
        - ""
        - "&8&l❙ &aRarity: %rarity%"
        - "&8&l❙ &aPrice: &210 &aCubes"
        - "&8&l❙ &aLevel Required: &f6"
        - "&8&l❙ &aPersonal Stock: &f%personal_stock%"
        - "&8&l❙ &aGlobal Stock: &f%global_stock%"
        - ""
        - "&8&l❙ &eClick here to buy"
      Glow: false
      Price: 10
      PersonalStock: 1
      GlobalStock: 50
      RequiredLevel: 6
      Actions:
        - "{console} give %player% sugar_cane 1"
        - "{message} &aYou received Sugar Cane!"
        - "{close}"